import {
	SiReact,
	SiTypescript,
	SiNextdotjs,
	SiReactquery,
	SiTrpc,
	SiHono,
	SiDrizzle,
	SiNodedotjs,
	SiBun,
	SiStyledcomponents,
	SiTailwindcss,
	SiChakraui,
	SiExpress,
	SiPostgresql,
	SiSvelte,
	SiSqlite,
	SiAmazondynamodb,
	SiMongodb,
	SiPrisma,
	SiMongoose,
	SiDocker,
	SiGithubactions,
	SiCypress,
	SiJest,
	SiVitest,
	SiMockserviceworker,
	SiBuddy,
    SiGraphql,
    SiTurborepo,
    SiRedis
} from '@icons-pack/svelte-simple-icons';

export const techIconMap: Record<string, any> = {
    'TailwindCSS': SiTailwindcss,
    'Redis': SiRedis,
	'React': SiReact,
	'TypeScript': SiTypescript,
	'NextJS': SiNextdotjs,
	'Next.js': SiNextdotjs,
	'React Query': SiReactquery,
	'tRPC': SiTrpc,
	'Hono': SiHono,
	'Drizzle ORM': SiDrizzle,
	'Drizzle': SiDrizzle,
	'NodeJS': SiNodedotjs,
	'Node.js': SiNodedotjs,
	'Bun': SiBun,
    'GraphQL': SiGraphql,
    'TurboRepo': SiTurborepo,
	'Styled-Components': SiStyledcomponents,
	'Chakra UI': SiChakraui,
	'Express': SiExpress,
	'PostgreSQL': SiPostgresql,
	'Svelte': SiSvelte,
    'SvelteKit': SiSvelte,
	'SQLite': SiSqlite,
	'DynamoDB': SiAmazondynamodb,
	'MongoDB': SiMongodb,
	'Prisma ORM': SiPrisma,
	'Prisma': SiPrisma,
	'Mongoose ORM': SiMongoose,
	'Mongoose': SiMongoose,
	'Docker': SiDocker,
	'GitHub Actions': SiGithubactions,
	'Cypress': SiCypress,
	'Jest': SiJest,
	'Vitest': SiVitest,
	'Mock Service Worker': SiMockserviceworker,
	'Buddy': SiBuddy,
};

export function getTechIcon(techName: string) {
	return techIconMap[techName] || null;
}
